// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserId               string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetModifyTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

type CreateRequest struct {
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{1}
}
func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (dst *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(dst, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateResponse struct {
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{2}
}
func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (dst *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(dst, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ReadRequest struct {
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadRequest) Reset()         { *m = ReadRequest{} }
func (m *ReadRequest) String() string { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()    {}
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{3}
}
func (m *ReadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadRequest.Unmarshal(m, b)
}
func (m *ReadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadRequest.Marshal(b, m, deterministic)
}
func (dst *ReadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadRequest.Merge(dst, src)
}
func (m *ReadRequest) XXX_Size() int {
	return xxx_messageInfo_ReadRequest.Size(m)
}
func (m *ReadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadRequest proto.InternalMessageInfo

func (m *ReadRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ReadResponse struct {
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{4}
}
func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (dst *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(dst, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{5}
}
func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(dst, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateResponse struct {
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{6}
}
func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(dst, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteRequest struct {
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{7}
}
func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(dst, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteResponse struct {
	Success              bool     `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_97f1d67a90c5ae84, []int{8}
}
func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(dst, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*CreateRequest)(nil), "account.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "account.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "account.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "account.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "account.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "account.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "account.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "account.DeleteResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _AccountService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _AccountService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _AccountService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_97f1d67a90c5ae84) }

var fileDescriptor_account_97f1d67a90c5ae84 = []byte{
	// 623 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0xd3, 0x34, 0x29, 0x13, 0x12, 0xa1, 0xa5, 0x90, 0xc8, 0x42, 0xaa, 0xf1, 0x01, 0x15,
	0x8b, 0xda, 0xad, 0x89, 0x2a, 0x91, 0x5e, 0x28, 0x70, 0x41, 0x48, 0x20, 0x19, 0x7a, 0xe1, 0x52,
	0x6d, 0xed, 0xa9, 0xe3, 0x2a, 0xf1, 0x6e, 0xbd, 0x6b, 0x0a, 0x42, 0x5c, 0xf8, 0x02, 0x04, 0x37,
	0x7e, 0x89, 0x23, 0xbf, 0xc0, 0x3f, 0x70, 0xe8, 0x05, 0x79, 0xd7, 0x8e, 0x6c, 0x9a, 0xaa, 0x3d,
	0x59, 0x33, 0xf3, 0xde, 0xdb, 0x37, 0x6f, 0x24, 0x43, 0x9f, 0x86, 0x21, 0xcb, 0x53, 0xe9, 0xf2,
	0x8c, 0x49, 0x46, 0xba, 0x65, 0x69, 0x6e, 0xc4, 0x8c, 0xc5, 0x33, 0xf4, 0x54, 0xfb, 0x28, 0x3f,
	0xf6, 0x64, 0x32, 0x47, 0x21, 0xe9, 0x9c, 0x6b, 0xa4, 0x79, 0xaf, 0x04, 0x50, 0x9e, 0x78, 0x34,
	0x4d, 0x99, 0xa4, 0x32, 0x61, 0xa9, 0x28, 0xa7, 0x8f, 0xd4, 0x27, 0xdc, 0x8a, 0x31, 0xdd, 0x12,
	0x67, 0x34, 0x8e, 0x31, 0xf3, 0x18, 0x57, 0x88, 0x8b, 0x68, 0xfb, 0x97, 0x01, 0xed, 0x03, 0x81,
	0x19, 0x19, 0x42, 0x37, 0x17, 0x98, 0x1d, 0x26, 0xd1, 0xc8, 0xb0, 0x8c, 0xcd, 0x1b, 0x41, 0xa7,
	0x28, 0x5f, 0x46, 0x64, 0x1d, 0x56, 0x71, 0x4e, 0x93, 0xd9, 0xa8, 0xa5, 0xda, 0xba, 0x20, 0x26,
	0xac, 0x71, 0x2a, 0xc4, 0x19, 0xcb, 0xa2, 0xd1, 0x8a, 0x1a, 0x2c, 0x6a, 0xb2, 0x07, 0xbd, 0x30,
	0x43, 0x2a, 0xf1, 0xb0, 0x70, 0x3e, 0x6a, 0x5b, 0xc6, 0x66, 0xcf, 0x37, 0x5d, 0xed, 0xda, 0xad,
	0xd6, 0x72, 0xdf, 0x55, 0x6b, 0x05, 0xa0, 0xe1, 0x45, 0xa3, 0x20, 0xcf, 0x59, 0x94, 0x1c, 0x7f,
	0xd2, 0xe4, 0xd5, 0xab, 0xc9, 0x1a, 0x5e, 0x34, 0x6c, 0x1f, 0xfa, 0xcf, 0x95, 0x54, 0x80, 0xa7,
	0x39, 0x0a, 0x49, 0xee, 0x43, 0xbb, 0x58, 0x43, 0x79, 0xef, 0xf9, 0x7d, 0xb7, 0x8a, 0xbc, 0x58,
	0x39, 0x50, 0x23, 0xfb, 0x21, 0x0c, 0x2a, 0x8e, 0xe0, 0x2c, 0x15, 0x58, 0x8f, 0xa2, 0x55, 0x8f,
	0xc2, 0x7e, 0x00, 0xbd, 0x00, 0x69, 0x54, 0x89, 0x5f, 0x8a, 0xdb, 0x81, 0x9b, 0x1a, 0x57, 0x0a,
	0x5e, 0xc3, 0xc5, 0x2b, 0xe8, 0x1f, 0xf0, 0xa8, 0xe6, 0xfc, 0xd2, 0x7b, 0x5c, 0x43, 0xcc, 0x81,
	0x41, 0x25, 0x56, 0x3a, 0x18, 0x41, 0x57, 0xe4, 0x61, 0x88, 0x42, 0x28, 0xde, 0x5a, 0x50, 0x95,
	0xf6, 0x26, 0xf4, 0x5f, 0xe0, 0x0c, 0x97, 0x3e, 0xdc, 0xdc, 0xca, 0x81, 0x41, 0x85, 0xbc, 0x4a,
	0xd5, 0x3f, 0x6f, 0xc1, 0x60, 0x5f, 0x1b, 0x7b, 0x8b, 0xd9, 0x87, 0x24, 0x44, 0xf2, 0x1a, 0x3a,
	0x3a, 0x67, 0x72, 0x77, 0xe1, 0xb9, 0x71, 0x2c, 0x73, 0x78, 0xa1, 0xaf, 0xdf, 0xb1, 0x6f, 0x7f,
	0xfd, 0xfd, 0xe7, 0x47, 0xab, 0x6f, 0xaf, 0x79, 0x25, 0x60, 0x62, 0x38, 0xe4, 0x0d, 0xb4, 0x8b,
	0x90, 0xc9, 0xfa, 0x82, 0x55, 0xbb, 0x8d, 0x79, 0xe7, 0xbf, 0x6e, 0xa9, 0x64, 0x2a, 0xa5, 0x75,
	0x42, 0x2a, 0x25, 0xef, 0x73, 0xb9, 0xec, 0x17, 0x72, 0x0a, 0x1d, 0x9d, 0x5a, 0xcd, 0x60, 0xe3,
	0x26, 0x35, 0x83, 0xcd, 0x78, 0xed, 0x5d, 0x25, 0xbb, 0x6d, 0x2e, 0x91, 0x9d, 0x18, 0xce, 0xfb,
	0xa1, 0xbf, 0x7c, 0x40, 0x0e, 0xa0, 0xa3, 0x23, 0xad, 0x3d, 0xd9, 0xb8, 0x46, 0xed, 0xc9, 0x66,
	0xf6, 0xd5, 0x26, 0xce, 0x12, 0xe5, 0x67, 0xe7, 0xc6, 0xf7, 0xfd, 0xbf, 0x06, 0xf9, 0x66, 0xc0,
	0x30, 0x66, 0x33, 0x9a, 0xc6, 0x6e, 0x9c, 0xf1, 0x70, 0xa1, 0x44, 0x79, 0x62, 0x73, 0xd8, 0xb8,
	0x64, 0x64, 0xf1, 0x8c, 0x9d, 0x60, 0x28, 0xc9, 0x93, 0xa9, 0x94, 0x5c, 0x4c, 0x3c, 0x2f, 0x4e,
	0xe4, 0x34, 0x3f, 0x72, 0x43, 0x36, 0xf7, 0x52, 0x16, 0x25, 0x54, 0x78, 0x57, 0x50, 0x4d, 0xa2,
	0x71, 0xe3, 0xdd, 0xa7, 0x71, 0xf1, 0xb7, 0x28, 0xa8, 0xfe, 0xca, 0x8e, 0xbb, 0xed, 0x18, 0x2d,
	0xff, 0x16, 0xe5, 0x7c, 0x96, 0x84, 0xea, 0x2f, 0xe4, 0x9d, 0x08, 0x96, 0x4e, 0x2e, 0x74, 0x82,
	0x3d, 0x58, 0x19, 0x6f, 0x8f, 0xc9, 0x18, 0x9c, 0x00, 0x65, 0x9e, 0xa5, 0x18, 0x59, 0x67, 0x53,
	0x4c, 0x2d, 0x39, 0x45, 0x2b, 0x43, 0xc1, 0xf2, 0x2c, 0x44, 0x2b, 0x62, 0x28, 0xac, 0x94, 0x49,
	0x0b, 0x3f, 0x26, 0x42, 0xba, 0xa4, 0x03, 0xed, 0x9f, 0x2d, 0xa3, 0x7b, 0xd4, 0x51, 0x3f, 0x89,
	0xc7, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x44, 0xbd, 0xe0, 0x60, 0x05, 0x00, 0x00,
}
