// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package account

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserId               string               `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	ModifyTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=modify_time,json=modifyTime,proto3" json:"modify_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *User) GetModifyTime() *timestamp.Timestamp {
	if m != nil {
		return m.ModifyTime
	}
	return nil
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{1}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{2}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ReadUsersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUsersRequest) Reset()         { *m = ReadUsersRequest{} }
func (m *ReadUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUsersRequest) ProtoMessage()    {}
func (*ReadUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{3}
}
func (m *ReadUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUsersRequest.Unmarshal(m, b)
}
func (m *ReadUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ReadUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUsersRequest.Merge(dst, src)
}
func (m *ReadUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUsersRequest.Size(m)
}
func (m *ReadUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUsersRequest proto.InternalMessageInfo

type ReadUsersResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUsersResponse) Reset()         { *m = ReadUsersResponse{} }
func (m *ReadUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUsersResponse) ProtoMessage()    {}
func (*ReadUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{4}
}
func (m *ReadUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUsersResponse.Unmarshal(m, b)
}
func (m *ReadUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ReadUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUsersResponse.Merge(dst, src)
}
func (m *ReadUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUsersResponse.Size(m)
}
func (m *ReadUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUsersResponse proto.InternalMessageInfo

func (m *ReadUsersResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type ReadUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{5}
}
func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (dst *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(dst, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

func (m *ReadUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ReadUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{6}
}
func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (dst *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(dst, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{7}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{8}
}
func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (dst *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(dst, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{9}
}
func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(dst, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type DeleteUserResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_account_183bb4b975caa63b, []int{10}
}
func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(dst, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "account.User")
	proto.RegisterType((*CreateUserRequest)(nil), "account.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "account.CreateUserResponse")
	proto.RegisterType((*ReadUsersRequest)(nil), "account.ReadUsersRequest")
	proto.RegisterType((*ReadUsersResponse)(nil), "account.ReadUsersResponse")
	proto.RegisterType((*ReadUserRequest)(nil), "account.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "account.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "account.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "account.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "account.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "account.DeleteUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountServiceClient is the client API for AccountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountServiceClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	ReadUsers(ctx context.Context, in *ReadUsersRequest, opts ...grpc.CallOption) (AccountService_ReadUsersClient, error)
	ReadUser(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) ReadUsers(ctx context.Context, in *ReadUsersRequest, opts ...grpc.CallOption) (AccountService_ReadUsersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AccountService_serviceDesc.Streams[0], "/account.AccountService/ReadUsers", opts...)
	if err != nil {
		return nil, err
	}
	x := &accountServiceReadUsersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AccountService_ReadUsersClient interface {
	Recv() (*ReadUsersResponse, error)
	grpc.ClientStream
}

type accountServiceReadUsersClient struct {
	grpc.ClientStream
}

func (x *accountServiceReadUsersClient) Recv() (*ReadUsersResponse, error) {
	m := new(ReadUsersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *accountServiceClient) ReadUser(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error) {
	out := new(ReadUserResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/ReadUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/account.AccountService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountServiceServer is the server API for AccountService service.
type AccountServiceServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	ReadUsers(*ReadUsersRequest, AccountService_ReadUsersServer) error
	ReadUser(context.Context, *ReadUserRequest) (*ReadUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_ReadUsers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AccountServiceServer).ReadUsers(m, &accountServiceReadUsersServer{stream})
}

type AccountService_ReadUsersServer interface {
	Send(*ReadUsersResponse) error
	grpc.ServerStream
}

type accountServiceReadUsersServer struct {
	grpc.ServerStream
}

func (x *accountServiceReadUsersServer) Send(m *ReadUsersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _AccountService_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).ReadUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).ReadUser(ctx, req.(*ReadUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/account.AccountService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "account.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _AccountService_CreateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _AccountService_ReadUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _AccountService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _AccountService_DeleteUser_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadUsers",
			Handler:       _AccountService_ReadUsers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "account.proto",
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_account_183bb4b975caa63b) }

var fileDescriptor_account_183bb4b975caa63b = []byte{
	// 671 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x4f, 0xd4, 0x5a,
	0x14, 0x4f, 0x87, 0x81, 0x81, 0x43, 0xe0, 0xc1, 0x7d, 0x2f, 0x8f, 0xd2, 0xf7, 0x0c, 0xb5, 0x2b,
	0x32, 0x81, 0x16, 0xc7, 0x91, 0xc4, 0xc1, 0x85, 0xa0, 0x1b, 0x57, 0x26, 0x55, 0x36, 0xc6, 0x04,
	0x2f, 0xed, 0xa1, 0x53, 0x32, 0xd3, 0x7b, 0xed, 0xbd, 0x15, 0x8d, 0x71, 0xe3, 0xce, 0x9d, 0xd1,
	0x9d, 0x9f, 0xc0, 0xef, 0xe2, 0xd2, 0xaf, 0xe0, 0x77, 0x70, 0xe1, 0xc6, 0xdc, 0xdb, 0x76, 0xa6,
	0x52, 0x2a, 0xb8, 0x6a, 0xee, 0x39, 0xbf, 0xf3, 0xfb, 0xfd, 0xce, 0x9f, 0x14, 0x96, 0x68, 0x10,
	0xb0, 0x2c, 0x91, 0x2e, 0x4f, 0x99, 0x64, 0xa4, 0x53, 0x3c, 0xad, 0x8d, 0x88, 0xb1, 0x68, 0x84,
	0x9e, 0x0e, 0x1f, 0x67, 0x27, 0x9e, 0x8c, 0xc7, 0x28, 0x24, 0x1d, 0xf3, 0x1c, 0x69, 0xfd, 0x5f,
	0x00, 0x28, 0x8f, 0x3d, 0x9a, 0x24, 0x4c, 0x52, 0x19, 0xb3, 0x44, 0x14, 0xd9, 0x2d, 0xfd, 0x09,
	0xb6, 0x23, 0x4c, 0xb6, 0xc5, 0x19, 0x8d, 0x22, 0x4c, 0x3d, 0xc6, 0x35, 0xa2, 0x8e, 0x76, 0xbe,
	0x18, 0xd0, 0x3e, 0x14, 0x98, 0x92, 0x35, 0xe8, 0x64, 0x02, 0xd3, 0xa3, 0x38, 0x34, 0x0d, 0xdb,
	0xd8, 0x5c, 0xf0, 0xe7, 0xd4, 0xf3, 0x41, 0x48, 0xfe, 0x81, 0x59, 0x1c, 0xd3, 0x78, 0x64, 0xb6,
	0x74, 0x38, 0x7f, 0x10, 0x0b, 0xe6, 0x39, 0x15, 0xe2, 0x8c, 0xa5, 0xa1, 0x39, 0xa3, 0x13, 0x93,
	0x37, 0xd9, 0x83, 0xc5, 0x20, 0x45, 0x2a, 0xf1, 0x48, 0x39, 0x37, 0xdb, 0xb6, 0xb1, 0xb9, 0xd8,
	0xb3, 0xdc, 0xdc, 0xb5, 0x5b, 0xb6, 0xe5, 0x3e, 0x2e, 0xdb, 0xf2, 0x21, 0x87, 0xab, 0x80, 0x2a,
	0x1e, 0xb3, 0x30, 0x3e, 0x79, 0x95, 0x17, 0xcf, 0x5e, 0x5e, 0x9c, 0xc3, 0x55, 0xc0, 0xd9, 0x85,
	0xd5, 0x7b, 0x9a, 0x4a, 0xb5, 0xe4, 0xe3, 0xf3, 0x0c, 0x85, 0x24, 0xd7, 0xa1, 0xad, 0x5a, 0xd1,
	0x6d, 0x2d, 0xf6, 0x96, 0xdc, 0x72, 0xec, 0x1a, 0xa3, 0x53, 0xce, 0x36, 0x90, 0x6a, 0x9d, 0xe0,
	0x2c, 0x11, 0xd8, 0x38, 0x12, 0x87, 0xc0, 0x8a, 0x8f, 0x34, 0x54, 0x60, 0x51, 0xa8, 0x28, 0xe9,
	0x4a, 0xac, 0x60, 0xb8, 0x82, 0x74, 0x17, 0xfe, 0x2a, 0xeb, 0x4a, 0xc3, 0x8d, 0xba, 0xb7, 0xa6,
	0xba, 0x7f, 0x22, 0xf1, 0x10, 0x56, 0x0f, 0x79, 0x78, 0x6e, 0x2a, 0x8d, 0xfb, 0x2e, 0x09, 0x5b,
	0xcd, 0x84, 0x2e, 0x90, 0x2a, 0x61, 0xe1, 0xc4, 0x84, 0x8e, 0xc8, 0x82, 0x00, 0x85, 0xd0, 0x8c,
	0xf3, 0x7e, 0xf9, 0x74, 0xb6, 0x60, 0xf5, 0x3e, 0x8e, 0xf0, 0x6a, 0x06, 0x14, 0x7b, 0x15, 0x7d,
	0x19, 0x7b, 0xef, 0x73, 0x1b, 0x96, 0xf7, 0x73, 0x93, 0x8f, 0x30, 0x7d, 0x11, 0x07, 0x48, 0x9e,
	0x01, 0x4c, 0xf7, 0x49, 0xac, 0x49, 0x0f, 0xb5, 0xe3, 0xb0, 0xfe, 0xbb, 0x30, 0x97, 0x6b, 0x3a,
	0xeb, 0x6f, 0xbf, 0x7e, 0xfb, 0xd8, 0xfa, 0xdb, 0x59, 0xf6, 0x0a, 0x90, 0xa7, 0x2c, 0x8a, 0x81,
	0xd1, 0x25, 0x4f, 0x61, 0x61, 0xb2, 0x6e, 0xb2, 0x3e, 0x21, 0x39, 0x7f, 0x16, 0x96, 0x75, 0x51,
	0xaa, 0xa0, 0xff, 0x57, 0xd3, 0xaf, 0x90, 0x73, 0xf4, 0x3b, 0x06, 0xa1, 0x30, 0x5f, 0xc2, 0x89,
	0x59, 0x63, 0x28, 0xb9, 0xd7, 0x2f, 0xc8, 0x14, 0xd4, 0xb6, 0xa6, 0xb6, 0x88, 0xf9, 0x2b, 0xb5,
	0xf7, 0xba, 0x18, 0xf9, 0x1b, 0xf2, 0xce, 0x00, 0x98, 0x2e, 0xb1, 0x32, 0xa3, 0xda, 0xa9, 0x54,
	0x66, 0x54, 0xdf, 0xba, 0x73, 0xa0, 0x95, 0xee, 0x58, 0x8d, 0x4a, 0x03, 0xa3, 0xfb, 0xe4, 0x5a,
	0xef, 0x77, 0x69, 0x12, 0x01, 0x4c, 0x37, 0x5e, 0xb1, 0x52, 0x3b, 0x9a, 0x8a, 0x95, 0xfa, 0x89,
	0x94, 0x4d, 0x77, 0x1b, 0xb5, 0x0e, 0x7e, 0x18, 0x1f, 0xf6, 0xbf, 0x1b, 0xe4, 0xbd, 0x01, 0x6b,
	0x11, 0x1b, 0xd1, 0x24, 0x72, 0xa3, 0x94, 0x07, 0x13, 0x4e, 0xca, 0x63, 0x87, 0xc3, 0x46, 0x43,
	0xca, 0xe6, 0x29, 0x3b, 0xc5, 0x40, 0x92, 0xdb, 0x43, 0x29, 0xb9, 0x18, 0x78, 0x5e, 0x14, 0xcb,
	0x61, 0x76, 0xec, 0x06, 0x6c, 0xec, 0x25, 0x2c, 0x8c, 0xa9, 0xf0, 0x2e, 0x29, 0xb5, 0x48, 0x8e,
	0xeb, 0xef, 0xde, 0x8d, 0xd4, 0x6f, 0x54, 0x95, 0xf6, 0x66, 0x6e, 0xb8, 0x3b, 0x5d, 0xa3, 0xd5,
	0x5b, 0xa1, 0x9c, 0x8f, 0xe2, 0x40, 0xff, 0x9e, 0xbd, 0x53, 0xc1, 0x92, 0x41, 0x2d, 0xe2, 0xef,
	0xc1, 0x4c, 0x7f, 0xa7, 0x4f, 0xfa, 0xd0, 0xf5, 0x51, 0x66, 0x69, 0x82, 0xa1, 0x7d, 0x36, 0xc4,
	0xc4, 0x96, 0x43, 0xb4, 0x53, 0x14, 0x2c, 0x4b, 0x03, 0xb4, 0x43, 0x86, 0xc2, 0x4e, 0x98, 0xb4,
	0xf1, 0x65, 0x2c, 0xa4, 0x4b, 0xe6, 0xa0, 0xfd, 0xa9, 0x65, 0x74, 0x8e, 0xe7, 0xf4, 0xdf, 0xf3,
	0xe6, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfa, 0xcc, 0x3f, 0x17, 0x79, 0x06, 0x00, 0x00,
}
